const SHOWDRAWER = "SHOWDRAWER";
const CLOSEDRAWER = "CLOSEDRAWER";
const ADDCREATIVE = "ADDCREATIVE";
const REMOVECREATIVE = "REMOVECREATIVE";

export { SHOWDRAWER, CLOSEDRAWER, ADDCREATIVE, REMOVECREATIVE };
