const COLOR_DATA_LOADING = "COLOR_DATA_LOADING";
const COLOR_DATA_SUCCESS = "COLOR_DATA_SUCCESS";
const COLOR_DATA_ERROR = "COLOR_DATA_ERROR";

export { COLOR_DATA_ERROR, COLOR_DATA_LOADING, COLOR_DATA_SUCCESS };
